language: php
php:
- '5.6'

script: echo "We don't have tests yet :("

before_deploy:
- sh config.sh
- sh package.sh

deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: dpdiU5uUR1Cz0bPjQksh23ldWVDucp3CAKLwzK2g3mWitwFN78mbuavUeA0LeWByma9R32I4EBexJLqUrz9JVUkAbWik6gswouezOE/yfhIIAeMr9Wh/Y281rWNgMO0Lp8UM64kr9ar3onfiWu8Q3Ottbd8i3Nz0KzDIyqlbf3uQyTb7ylikdUYdRu8XfDb2BpDYY0r7tM58NT3hjO33210698uD8c/bhn+jMS24lfbM2BU4P2ae03b9Z5K6/UgbdDemxRlXEgm8bk2AjIBx/S9zVcyuvRwa8TLNKubH2wiwbfV1Q8Kryk25KcR/OgGXa5KwH18n0mjY1MrjiYeZnftY+ar7E3hIERw99+yEMK/pi33v4xel6OxYyiDPAFggPuQla0TSijsgvPoZemwqpqPR2lFgsEIVLtwuD4b0Km28qelopVJYGmSyXE2Kn2mUUm40mPTx5uJtRP+M4s83PJhbIbqzisSFoNHc8tOVWPqN2/GDE188SHTAngGlrYDznb3rhi/sLwbYLzZa1I/9hBVqa97SB7YDP0cnkYti9+8lOdtBonp/8jQkcONMG8y7gDhCuXnMLtcDvgv/BWNTmGp04GOqg5awZbUCXuGGgLQcf/lnkltAQplV50hElKoNcuq4kAWsstMjKnGPJll2Gfjsa6n4OteEfinswaPUv08=
  file: "plugin-transbank-webpay-virtuemart3-$TRAVIS_TAG.zip"
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-virtuemart-webpay
    tags: true
